image: bitbucketpipelines/scala-sbt:scala-2.12

pipelines:
  default:
    - step:
        caches:
            - sbt
            - ivy2
        script:
          - java -XX:+UnlockDiagnosticVMOptions -XX:+PrintFlagsFinal -version -XX:+UseG1GC | grep Metaspace
