image: bitbucketpipelines/scala-sbt:scala-2.12

pipelines:
  default:
    - step:
        caches:
            - sbt
            - ivy2
        script:
          - sbt sbtVersion
          - sbt +clean
          - sbt +test
          - sbt +kiama/package +kiama/packageSrc +kiama/package-doc
          - sbt +kiama/test:package +kiama/test:packageSrc +kiama/test:packageDoc
